### ISSUE TITLE
Move tetrominos instead of redrawing every tick

### ISSUE THREAD

**Issue by dealingwith** [MinecraftU/2021-computer-adventures#19]

**Comment by dealingwith** [comment]
http://www.ruby2d.com/learn/2d-basics/#example-of-moving-a-square-shape-with-keys

**Comment by jamespeilunli** [comment]
I think literally moving the squares would be more complicated; I think we should just still draw from the matrix, but have an array with the squares and calling `.remove` on each square instance in the array. [source](https://www.ruby2d.com/learn/2d-basics/#adding-and-removing-objects). But it appears that you can also call `.add` to add the square back to the screen, so this might not work (but at least the things won't be drawn, which should be the major source of the lag).

**Comment by jamespeilunli** [comment]
Using my idea, this:
```
  def draw(start_pos, size) # size is the side length of a square
    (0...gameboard.width).each do |i|
      (0...gameboard.height).each do |j|
        if squares[j, i] != 0
          squares[j, i].remove # Ruby2D::Square#remove method https://www.ruby2d.com/learn/2d-basics/#adding-and-removing-objects
        end
        if gameboard[j, i] != 0
          color = color_map[gameboard[j, i]] 
          # draws a square starting at point (x, y) with side length size and color color. z is the layer (the higher z is, the higher on the layers the shape is)
          squares[j, i] = Square.new(
            x: start_pos[0] + size*i, y: start_pos[1] + size*j,
            size: size,
            color: color,
            z: 10
          )
        end
      end
    end
  end
```
`draw` method and adding `set background: "white"` to `tetris.rb`, there was no more lag.

**Comment by dealingwith** [comment]
![make it so](https://media1.giphy.com/media/wNlks0ID1igO4/giphy.gif?cid=ba572133t22g1yq4tkkq5yury8xrum7rzxsbnndhrj0ga0cd&rid=giphy.gif&ct=g)
