### ISSUE TITLE
RFC: Graphical Tetris Game

### ISSUE THREAD

**Issue by jamespeilunli** [MinecraftU/2021-computer-adventures#3]
# Overview

I used to really like to play the clasic game Tetris. I'd open up a Tetris game and a Twitch stream I like to listen to on my browser, and I could play for hours. 

The project I would like to make is a simple recreation of Tetris in Ruby. The game will not be text based and will have basic graphics.

# The Problem

## Background & Motivation

You may have noticed that the first paragraph in Overview was in past tense. This is because now, I feel that playing video games for a long time is unproductive and hurts my eyes. That's why I can't just go ahead and pull up Tetris on my browser. That's why I need an excuse -- I mean reason -- to go play Tetris for a while. If the Tetris game I'm playing is coded by myself, playing Tetris would be justified as a reward for making the game. 

# Solution

## Goals

I would be very statisfied if I could make something pretty similar to [this](https://tetris.com/play-tetris/).

### The following criteria should be met when the game is complete:
* Shapes made out of multiple squares can 
    1. Fall down the screen 
    2. Be controlled by the player (can move left and right and can rotate)
    3. Land without interfering with other shapes
* When a row is completeley filled with squares, the row disappears and all squares move down one space.

### It'd be great if some of this additional optional criteria is met too:
* Shapes can
    1. Be accelerated faster than the normal rate down the screen
    2. Instantly land
* There are points which 
    1. Are gained by row deletion
    2. Make the shape falling rate faster
* There is a user interface (UI) (like a menu with buttons like start, high scores, etc.; pause and resume buttons)
* Customizable everything (maybe a customize mode), including customizable
    1. Shapes
    2. Fall speed
    3. Points to fall speed ratio
    4. Gameboard size (change from default 10x20 squares to something else)
    5. Keyboard bindings (eg. switch arrow keys to WASD), keyboard and mouse modes

## Non-goals

* Not a web app; runs locally
* Not text-based; there are graphics
* Graphics don't need to be super fancy (eg. squares can be just one color, UI doesn't have to be great, no need for animations)

## Dependencies

I'll need something similar to [Ruby2D](http://www.ruby2d.com/), a library similar to [Pygame](https://www.pygame.org/docs/), that renders graphics on a window.

## Alternatives/Prior Art

* [A Tetris website](https://tetris.com/play-tetris)
* [A Tetris game using Ruby2D](https://github.com/Nakilon/rbtris)

## Design

* Object-oriented
* Use a [matrix](https://ruby-doc.org/stdlib-2.5.1/libdoc/matrix/rdoc/Matrix.html) for gameboard?

**Comment by dealingwith** [comment]
1. I love Tetris too! My wife and I play Tetris on the Switch (almost) every night after dinner. 😄 
1. The fact that it's just Tetris makes the requirements really clear, we wouldn't have to discuss requirements...project-wise, that's great, educationally, less so 😂 ...you've already broken up the "must have" features and the "nice to have" features, which is great
1. I really like that there is [already a github repo](https://github.com/Nakilon/rbtris) using the Ruby2D library to create a Tetris game--this would allow us to learn from them and probably speed up our development, allowing us to make something really awesome (at least relatively)
1. I'm assuming all the art we could download off the internet any art we would need for this

**Comment by dealingwith** [comment]
* Executed from the cmd line

**Comment by jamespeilunli** [comment]
For additions we might want to try meet all the specifics of Tetris (check [Tetris Wiki](https://tetris.fandom.com/wiki/Tetris_Wiki)). There's very specific scoring systems, sounds, etc.

**Comment by dealingwith** [comment]
WINNER!
