### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by dealingwith** [MinecraftU/2021-computer-adventures#58]

**Comment by jamespeilunli** [comment]
Is the leaderboard going to have multiple people on it? If so, how do we achieve that?

**Comment by dealingwith** [comment]
I think we should accept three initials like the old-school arcade game.
Then we'll have to write the leaderboard to a file to persist it across
games.

>

**Comment by jamespeilunli** [comment]
Sounds good. So this file wont be the same across different devices right?

**Comment by dealingwith** [comment]
Same file name, different contents stored locally on each machine.

>
