### ISSUE TITLE
De-randomize new tetromino generation

### ISSUE THREAD

**Issue by dealingwith** [MinecraftU/2021-computer-adventures#59]
- Don't let the same tetromino spawn 2x in a row
- Favor a long block after N tetrominoes
  - but also don't spawn too many long blocks

**Comment by jamespeilunli** [comment]
[This r/dailyprogrammer post](https://www.reddit.com/r/dailyprogrammer/comments/3ofsyb/20151012_challenge_236_easy_random_bag_system/) states:
> Contrary to popular belief, the tetromino pieces you are given in a game of Tetris are not randomly selected. Instead, all seven pieces are placed into a "bag." A piece is randomly removed from the bag and presented to the player until the bag is empty. When the bag is empty, it is refilled and the process is repeated for any additional pieces that are needed.
In this way, it is assured that the player will never go too long without seeing a particular piece. It is possible for the player to receive two identical pieces in a row, but never three or more. Your task for today is to implement this system.

This seems like a good way to implement "Don't let the same tetromino spawn 2x in a row".

**Comment by jamespeilunli** [comment]
It'll also make implementing some sort of "Next n pieces" like on [tetris.com/play-tetris](https://tetris.com/play-tetris):
![image](https://user-images.githubusercontent.com/68968548/135725397-4c865ba1-e7e4-468a-a81a-7e3781b184c6.png)
easier. (see "next" box to the right of the gameboard)
